@echo off
echo تشغيل تطبيق مدير المنطقة...
echo.
echo تثبيت المكتبات المطلوبة...
pip install pandas flask flask-sqlalchemy flask-login flask-migrate flask-wtf werkzeug python-dotenv
echo.
echo تشغيل التطبيق...
python app.py
